[env:esp32s3-supermini]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

board_build.flash_size = 4MB
board_build.partitions = huge_app.csv

lib_deps =
  adafruit/Adafruit GFX Library @ ^1.11.9
  adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3
  bblanchon/ArduinoJson @ ^7.0.4
  h2zero/NimBLE-Arduino @ ^1.4.2

build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_LOOP_STACK_SIZE=16384
  -D CONFIG_ESP32S3_BROWNOUT_DET=0
